### ISSUE TITLE
Add extra command arguments field

### ISSUE THREAD

**Issue by mborgerson** [xqemu/xqemu-manager#10]
For some advanced features, would be good to have a box for any extra args that aren't handled by the GUI.

**Comment by JayFoxRox** [comment]
I have prototyped this here: https://github.com/JayFoxRox/xqemu-manager/pull/2

I'd appreciate if someone took over (feel free to use any / all of my code, or start from scratch - whatever you want to do).

**Comment by JayFoxRox** [comment]
Closed by PR #25
