### ISSUE TITLE
Reported command line and what is ran could diverge

### ISSUE THREAD

**Issue by JayFoxRox** [xqemu/xqemu-manager#29]
There is a discrepancy of what xqemu-manager claims to run (`launchCmdToString(cmd)`), and what is actually being ran (`cmd`).

There could be cases where `launchCmdToString` and the expansion in `subprocess.Popen` diverge. So copy pasting the "Running: ..." line from stdout might not produce the same result as running it through xqemu-manager.

**Comment by thrimbor** [comment]
I'm not sure what a good solution to this would look like.

My first idea was to somehow get the internal call string from Python. But while Python uses list2cmdline (which is not supposed to be relied upon by external code) on Windows, it doesn't seem to touch the argument list at all on POSIX systems, instead [passing it through all the way to execv](https://github.com/python/cpython/blob/master/Modules/_posixsubprocess.c#L509).

So if we want to have a shell-compatible call string, we'll probably have to generate it ourselves. The shlex module [might be helpful](https://docs.python.org/3/library/shlex.html#shlex.quote) for this, but it's Python 3 only (and we'd have to copy the list2cmdline behavior for Windows).

(I only did some reading, I'm not actively working on this atm)

**Comment by JayFoxRox** [comment]
I believe this was fixed in #48.
`QProcess` uses `launchCmdToString` now.

How different shells and `QProcess` interpret the command line could still diverge, but we can never avoid that.
